spring:
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false

logging:
  level:
    root: WARN
    com.sesac.msa: INFO

info:
  environment: "Production"
  debug: false
